In [26]:
import sys
import argparse
import torch

torch.set_printoptions(profile="full")

sys.path.append('/home/ajliang/search/search')

from utils.common_utils import load_model
from map2map.map2map.data.fields import FieldDataset

"""Load Dataset"""
device = torch.device('cpu')

args = argparse.Namespace(
    init_input_path="/user_data/ajliang/Linear/val/LH0045/4/dis.npy",
    style_path="/user_data/ajliang/Linear/val/LH0045/4/params.npy",
    target_output_path="/user_data/ajliang/Nonlinear/val/LH0045/4/dis.npy",
    load_backward_model_state="/home/ajliang/search/model_weights/backward_model.pt",
    verbose=False,
    dropout_prob=0.0,
    crop=3,
)

with_padding_dataset = FieldDataset(
    style_pattern=args.style_path,
    in_patterns=[args.init_input_path],
    tgt_patterns=[args.target_output_path],
    # in_norms=['cosmology.dis'],
    callback_at='/home/ajliang/search/search/map2map',
    crop=args.crop,
    in_pad=2,
)

In [10]:
data = dataset[0]

In [11]:
input = data['input']
# add batch dimension
input = input.unsqueeze(0)

In [12]:
input

tensor([[[[[ 2.7994e+00,  1.9596e+00,  1.1646e+00, -7.5025e-01, -1.2989e+00,
            -1.9596e-01,  6.8866e-01],
           [ 1.7469e+00,  8.3423e-01,  2.2396e-02, -1.0526e+00, -1.4669e+00,
            -4.5911e-01,  1.4557e-01],
           [ 1.2486e+00, -1.8756e+00, -1.9372e+00, -2.0492e+00, -1.1758e+00,
            -6.3827e-01, -6.8866e-01],
           [ 9.3501e-01, -2.8218e+00, -4.0648e+00, -3.9640e+00, -2.8778e+00,
            -1.8140e+00, -2.1724e+00],
           [ 2.0436e+00, -1.1926e+00, -4.0088e+00, -5.0558e+00, -3.7289e+00,
            -2.9450e+00, -2.5979e+00],
           [ 3.1970e+00,  7.8944e-01, -2.0492e+00, -4.2663e+00, -4.3895e+00,
            -3.6505e+00, -3.0850e+00],
           [ 2.3907e+00,  4.0872e-01, -1.2486e+00, -2.8050e+00, -3.2697e+00,
            -3.2138e+00, -3.5385e+00]],

          [[ 2.0772e+00,  3.1354e-01,  8.1184e-01,  1.5453e+00,  1.2094e+00,
             8.4543e-01,  9.7421e-01],
           [ 2.3683e+00, -6.2707e-01, -6.7187e-01,  2.0716e-01,  6.158

In [13]:
dataset = FieldDataset(
    style_pattern=args.style_path,
    in_patterns=[args.init_input_path],
    tgt_patterns=[args.target_output_path],
    # in_norms=['cosmology.dis'],
    callback_at='/home/ajliang/search/search/map2map',
    crop=args.crop,
)

In [14]:
no_pad_data = dataset[0]

In [15]:
no_pad_input = no_pad_data['input']
no_pad_input = no_pad_input.unsqueeze(0) # add batch dimension

In [16]:
no_pad_input

tensor([[[[[  2.0135,   2.2359,   1.2593],
           [  2.0751,   1.9687,   0.3752],
           [  1.8954,   1.7060,   0.5028]],

          [[  6.1002,   3.8873,   1.9332],
           [  5.1050,   2.6013,   0.4547],
           [  1.7198,   1.3248,   0.6123]],

          [[  3.7927,   2.9611,   2.0979],
           [  2.9201,   2.5255,   2.4938],
           [  1.0762,   1.6376,   1.1259]]],


         [[[  4.4370,   5.6015,   5.5496],
           [  6.4962,   4.9833,   4.4043],
           [  6.6405,   4.6103,   2.8258]],

          [[  4.7722,   5.3540,   4.0201],
           [  5.0593,   3.7248,   3.8242],
           [  4.0240,   4.0246,   2.8780]],

          [[  4.9387,   5.3324,   4.3888],
           [  2.9496,   2.4823,   3.0430],
           [  1.1731,   2.9347,   2.5989]]],


         [[[-12.1216,  -8.4961,  -9.6606],
           [-12.4911,  -8.6464, -10.0244],
           [-13.3589, -10.8246, -10.0793]],

          [[-12.3007, -10.3704, -11.1817],
           [-12.4127, -11.4687, -11.

In [24]:
import torch.nn.functional as F

padded_input = F.pad(no_pad_input, (2, 2, 2, 2, 2, 2), mode='circular')

In [25]:
padded_input == input

tensor([[[[[False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False]],

          [[False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False]],

          [[False, False, False, False, False, False, False],
           [False, False, False, False, False, False, False],
    

In [28]:
with_padding_dataset.in_pad[slice(None)]

array([[2, 2],
       [2, 2],
       [2, 2]])